version: '3.4'

services:
  apigateway:
    container_name: apigateway
    image: fabricdemo/apigateway:${TAG:-latest}
    network_mode: host
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:54479
    ports:
      - "54479:54479"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  identityserver:
    container_name: identityserver
    image: fabricdemo/identityserver:${TAG:-latest}
    network_mode: host
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:54452
    ports:
      - "54452:54452"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  productservice:
    container_name: productservice
    image: fabricdemo/productservice:${TAG:-latest}
    network_mode: host
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:55121
    ports:
      - "55121:55121"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  userservice:
    container_name: userservice
    image: fabricdemo/userservice:${TAG:-latest}
    network_mode: host
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:54045
    ports:
      - "54045:54045"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro